# Generated by Django 5.1.6 on 2025-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ispopular',
            field=models.BooleanField(default=False),
        ),
    ]
