# Generated by Django 5.1.6 on 2025-03-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_transactions_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='ref',
        ),
    ]
